apiVersion: v1
kind: Pod
metadata:
  name: hellow.com
  labels:
    app: hellow
spec:
  containers:
    - name: demo-k8s
      image: wardviaene/k8s-demo
      ports:
        - name: nodejs-port
          containerPort: 3000