apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-hellow
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hellow
  template:
    metadata:
      labels:
        app: hellow
    spec:
      containers:
        - name: k8s-demo
          image: wardviaene/k8s-demo
          ports:
            - name: nodejs-port
              containerPort: 3000
