apiVersion: v1
kind: Pod
metadata:
  name: pod-db
  labels:
    app: pod-db
spec:
  containers:
  - name: mysql
    image: mysql:8
    ports:
    - name: mysql-port
      containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: secrets-db
            key: rootPassword
      - name: MYSQL_USER
        valueFrom:
          secretKeyRef:
            name: secrets-db
            key: username
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: secrets-db
            key: password
      - name: MYSQL_DATABASE
        valueFrom:
          secretKeyRef:
            name: secrets-db
            key: database
