apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-secretes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: secrete
  template:
    metadata:
      labels:
        app: secrete
    spec:
      containers:
      - name: k8s-demo
        image: wardviaene/k8s-demo
        ports:
        - name: nodejs-port
          containerPort: 3000
        volumeMounts:
        - name: cred-volume
          mountPath: /etc/creds
          readOnly: true
      volumes:
      - name: cred-volume
        secret:
          secretName: db-secrets
