apiVersion: v1
kind: ReplicationController
metadata:
  name: repl-hellow
spec:
  replicas: 2
  selector:
    app: hellow_repl
  template:
    metadata:
      labels:
        app: hellow_repl
    spec:
      containers:
        - name: k8s-demo
          image: wardviaene/k8s-demo
          ports:
            - name: nodejs-port
              containerPort: 3000
